### ISSUE TITLE
Catch error 404 on getLegal call

### ISSUE THREAD

**Issue by AlexandreGombert** [RedFroggy/ilg-spring-boot-starter#73]
https://github.com/RedFroggy/ilg-spring-boot-starter/blob/8025150053527439358ba598ee99fb5adeeb4a1e/src/main/java/fr/redfroggy/ilg/client/legalinformation/LegalInformationApi.java#L65

When I call LegalInformationApi.getLegal('FR', '850833492'), I got an error 404.
Seems to fail when legalInfo are not in ILG.

Alexandre, from Conformitee.

**Comment by dajay** [comment]
Solution is to add decode404 property, when decode404 is true then the client return empty response and not throw exception on status 404.
